[package]
name = "xinput"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty-xinput = "1.2.0"
crossterm = "0.17"
tui = { version = "0.9", default-features = false, features = ['crossterm'] }
